"""
Central configuration for the Catalog RAG assistant.
All tuneable knobs live here — never scattered across modules.
"""
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# ── Directory layout ──────────────────────────────────────────────────────────
BASE_DIR         = Path(__file__).parent.resolve()
DATA_DIR         = BASE_DIR / "data"
RAW_DIR          = DATA_DIR / "raw"  # PDFs: raw/Course Pages/, Program Pages/, etc.
PROCESSED_DIR    = DATA_DIR / "processed"
VECTOR_STORE_DIR = BASE_DIR / "vector_store"
TRANSCRIPTS_DIR  = BASE_DIR / "transcripts"
DEMO_DIR         = BASE_DIR / "demo"

# Ensure required directories exist on import
for _d in [RAW_DIR, PROCESSED_DIR, VECTOR_STORE_DIR, TRANSCRIPTS_DIR, DEMO_DIR]:
    _d.mkdir(parents=True, exist_ok=True)

# ── Chunking ──────────────────────────────────────────────────────────────────
CHUNK_SIZE    = 500   # tokens — wide enough to capture full prereq statements
CHUNK_OVERLAP = 100   # token overlap — prevents splitting prereq sentences at boundaries

# ── Embeddings ────────────────────────────────────────────────────────────────
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DEVICE = "cpu"

# ── LLM (Groq — free tier) ────────────────────────────────────────────────────
GROQ_API_KEY    = os.getenv("GROQ_API_KEY", "")
LLM_MODEL       = "llama-3.1-8b-instant"
LLM_TEMPERATURE = 0.0    # deterministic — critical for repeatable prereq decisions
LLM_MAX_TOKENS  = 1024  # safe with 65s inter-query sleep — full TPM window per query

# ── Gradio demo ───────────────────────────────────────────────────────────────
# If you see WinError 10048, either stop the other process on 7860 or set e.g.
#   GRADIO_SERVER_PORT=7861  in .env
GRADIO_SERVER_PORT = int(os.getenv("GRADIO_SERVER_PORT", "7860"))

# ── Retriever ─────────────────────────────────────────────────────────────────
RETRIEVER_K           = 6    # chunks returned per sub-query
RETRIEVER_FETCH_K     = 20   # candidate pool before MMR re-ranking
RETRIEVER_LAMBDA_MULT = 0.7  # MMR diversity weight (0=max diversity, 1=max relevance)
MULTI_QUERY_COUNT     = 3    # sub-queries generated by MultiQueryRetriever

# ── Vector store ──────────────────────────────────────────────────────────────
FAISS_INDEX_NAME = "catalog_index"

# ── Scraper ───────────────────────────────────────────────────────────────────
SCRAPER_DELAY       = 1.5   # polite delay between requests (seconds)
SCRAPER_TIMEOUT     = 15    # per-request timeout (seconds)
SCRAPER_MAX_RETRIES = 3     # retry attempts on transient failures
SCRAPER_USER_AGENT  = (
    "Mozilla/5.0 (compatible; catalog-rag-assistant/1.0; +research-use)"
)

# ── Metadata ──────────────────────────────────────────────────────────────────
METADATA_FILE    = DATA_DIR / "metadata.json"
DATE_ACCESSED    = "2026-03-29"

# ── Evaluation ────────────────────────────────────────────────────────────────
EVAL_RESULTS_FILE = BASE_DIR / "evaluation_report.json"
EVAL_CSV_FILE     = BASE_DIR / "evaluation_results.csv"

# Indices (0-based) of queries to save as required example transcripts:
#   transcript_1 — correct eligibility decision with citations   (query index 2)
#   transcript_2 — course plan output with justification         (special plan query)
#   transcript_3 — correct abstention + guidance                 (query index 20)
TRANSCRIPT_INDICES = {
    "transcript_1_eligibility": 2,
    "transcript_3_abstention":  20,
}
